
services:
  app:
    image: movieapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - movie_network

  webserver:
    image: nginx:alpine
    container_name: movie_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - movie_network

  db:
    image: mysql:8.0
    container_name: movie_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - movie_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: movie_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel_user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    networks:
      - movie_network

  composer:
    image: composer:latest
    container_name: movie_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]

volumes:
  dbdata:

networks:
  movie_network:
    driver: bridge